#YAML is another form to store data
commands:
  # Time
  - command:
    input: What time is?
    entity: time
    action: getTime
  - command:
    input: Tell me the time
    entity: time
    action: getTime
  #Date
  - command:
    input: What day is?
    entity: time
    action: getDate
  - command:
    input: Tell me the date
    entity: time
    action: getDate
  # Year
  - command:
    input: Tell me which year is
    entity: time
    action: getYear
  - command:
    input: which year is it?
    entity: time
    action: getYear
  #Weather 
  - command:
    input: What is the weather?
    entity: time
    action: getWeather
  - command:
    input: What is the weather like?
    entity: time
    action: getWeather
  # Open
  - command:
    input: Open Opera
    entity: open
    action: opera